# Functions of Numpy Part-2

In [1]:
import numpy as np

In [3]:
# reshape function
a=np.arange(18)
print(a,"\n")
a1=np.reshape(a,(3,6))
print(a1,"\n")
a3=np.reshape(a,(3,6),order='F')
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

[[ 0  3  6  9 12 15]
 [ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]]


In [9]:
b1=np.arange(12)
b2=np.reshape(b1,(4,3),order='F')  
print(b2,"\n") 
#b3=np.reshape(np.ravel(b1, order='F'), (4, 3), order='F')
#print(b3,"\n")
b4=np.reshape(b1, (4,-1))  
print(b4)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# sum
c1=np.arange(12)
print(c1,"\n")
c2=np.sum(c1)
print("sum is :",c2)
c3=np.sum(c1,dtype=np.float32)
print("sum is",c3)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

sum is : 66
sum is 66.0


In [10]:
d1=np.arange(12).reshape(3,4)
print(d1,"\n")
d2=np.sum(d1,axis=1)
print("sum row wise",d2)
d3=np.sum(d1,axis=0)
print("sum column wise", d3)
d4=np.sum(10)
print(d4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

sum row wise [ 6 22 38]
sum column wise [12 15 18 21]
10


In [8]:
# random function
e1=np.random.rand(3,2)  
print(e1,"\n")
e2=np.random.randn(2,2)  
print(e2,"\n")
e3=np.random.randint(10,size=5)  
print(e3,"\n")
e4=np.random.random_integers(5, size=(3,2))  
print(e4,"\n")

[[0.74156091 0.64310994]
 [0.02433887 0.57278331]
 [0.33277662 0.26581522]] 

[[-0.63536845 -0.40296082]
 [-0.35996897 -0.43288255]] 

[8 0 9 4 9] 

[[1 3]
 [3 2]
 [2 2]] 



C:\Users\1648s\AppData\Local\Temp\ipykernel_968\856442658.py:8: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  e4=np.random.random_integers(5, size=(3,2))


In [4]:
# zeros function
f1=np.zeros((3,2),dtype=float)
print(f1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
# where function
g1=np.arange(10)  
g2=np.where(g1<4,g1,5*g1)  
print(g2) 

[ 0  1  2  3 20 25 30 35 40 45]
