# Functions of Numpy Part-4

In [1]:
import numpy as np

In [2]:
# average function
a1 = list(range(1,6))  
a2 =np.average(a1)  
print (a1,"\n") 
print (a2)

[1, 2, 3, 4, 5] 

3.0


In [3]:
# pad function
b1 = [1, 3, 2, 5, 4]  
b2 = np.pad(b1, (3, 2), 'constant', constant_values=(6, 4))  
print (b2)

[6 6 6 1 3 2 5 4 4 4]


In [4]:
# ravel function
c1 = np.array([[1, 3, 5], [11, 35, 56]])  
c2 =np.ravel(c1) 
print (c2)

[ 1  3  5 11 35 56]


In [6]:
# fix function
d1 = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",d1)  
d2 = np.fix(d1)  
print("Output array:",d2) 


Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]


In [8]:
# arccos function
e1 = [0, 0.3, -1]   
print ("Input array : \n", e1)   
e2 = np.arccos(e1)   
print ("\nInverse cos values : \n", e2)  

Input array : 
 [0, 0.3, -1]

Inverse cos values : 
 [1.57079633 1.26610367 3.14159265]


In [9]:
# arcsin function 
f1 = [0, 0.3, -1]   
print ("Input array : \n", f1)   
f2 = np.arcsin(f1)   
print ("\nInverse Sine values : \n", f2)   

Input array : 
 [0, 0.3, -1]

Inverse Sine values : 
 [ 0.          0.30469265 -1.57079633]


In [10]:
# arctan function
g1 = [0, 0.3, -1]   
print ("Input array : \n", g1)   
g2= np.arctan(g1)   
print ("\nInverse tan values : \n", g2)   

Input array : 
 [0, 0.3, -1]

Inverse tan values : 
 [ 0.          0.29145679 -0.78539816]
