# Functions of Numpy Part-3

In [18]:
import numpy as np  
 

In [17]:
# argsort function
a=np.array([[1,6],[2,5]])    
a1=np.argsort(a,axis=0)  
print(a1,"\n")
np.take_along_axis(a, a1, axis=0) 

[[0 1]
 [1 0]] 



array([[1, 5],
       [2, 6]])

In [21]:
# mean function
b1= np.array([[1, 2], [3, 4]])  
b2=np.mean(b1,axis=0) 
b3=np.mean(b1,axis=1)  
print(b2) 
print(b3) 

[2. 3.]
[1.5 3.5]


In [30]:
# unique function 
c1 = np.array([[1, 1],[2,3],[2,3],[1,1],[2,2],[3,3]])  
c2=np.unique(c1, axis=0)  
c3=np.unique(c1, axis=1)  
print(c2,"\n")
print(c3)

[[1 1]
 [2 2]
 [2 3]
 [3 3]] 

[[1 1]
 [2 3]
 [2 3]
 [1 1]
 [2 2]
 [3 3]]


In [33]:
# tolist function
d1 = np.array([[11, 21], [31, 41]])  
d2=d1.tolist()
print(d1,"\n")
print(d2) 

[[11 21]
 [31 41]] 

[[11, 21], [31, 41]]


In [34]:
# dot operater
e1 =np.dot(6,12)  
print(e1)  

72


In [35]:
# ceil function

f1 = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",f1)  
f2 = np.ceil(f1)  
print("Output array:",f2)  
  

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [ 1.  1.  2.  2. 10.]


In [36]:
# floor function

g1 = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",g1)  
g2 = np.floor(g1)  
print("Output array:",g2)  
  

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]
