# Functions of Numpy Part-5

In [8]:
import numpy as np
import math
import numpy.matlib

In [2]:
# rint function
a1 = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",a1)  
a2= np.rint(a1)  
print("Output array:",a2)  

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [ 0.  0.  1.  1. 10.]


In [5]:
# tanh function
b1 = np.array([0, math.pi/4, 3*math.pi/2, math.pi/6])  
print("Input Array:",b1)  
print("tanh Array:",end=" ")  
b2= np.tanh(b1)  
print(b2)  

Input Array: [0.         0.78539816 4.71238898 0.52359878]
tanh Array: [0.         0.6557942  0.99983861 0.48047278]


In [6]:
# trunc function
c1 = [0.23, 0.09, 1.2, 1.24, 9.99]  
print("Input array:",c1)  
c2 = np.trunc(c1)  
print("Output array:",c2)  

Input array: [0.23, 0.09, 1.2, 1.24, 9.99]
Output array: [0. 0. 1. 1. 9.]


In [11]:
# eye function

print(numpy.matlib.eye(n=3,k=0,dtype=float))  

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# identity function

print(numpy.matlib.identity(4))    

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# ones function

print(numpy.matlib.ones((3,3)))    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# zeros function

print(numpy.matlib.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# frombuffer function

d1 = b'hello world'  
print(type(d1))  
d2= np.frombuffer(d1, dtype = "S1")  
print(d2)  
print(type(d2))  

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [20]:
# fromiter function

e1 = [0,2,4,6]  
e2 = iter(list)  
e3 = np.fromiter(e2, dtype = float)  
print(e3)  
print(type(e3))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [21]:
# linespace function

f1 = np.linspace(10, 20, 5)  
print("The array over the given range is ",f1)  

The array over the given range is  [10.  12.5 15.  17.5 20. ]


In [22]:
# logspace function

g1 = np.logspace(10, 20, num = 5, endpoint = True)  
print("The array over the given range is ",g1)  

The array over the given range is  [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]
