# Functions of Numpy Part-1

import numpy as np

In [31]:
#print array
x = np.array([[2,5,10,8]])
y = np.array([[1,5,9,5],[2,9,7,1]])
z = np.array([[[1.1,5.7,7,9],[2,7.1,8,9],[3,4,9.0,8]]])
print("This id 1D Array:")
print(x,"\n")
print("This id 2D Array:")
print(y,"\n")
print("This id 3D Array:")
print(z)

This id 1D Array:
[[ 2  5 10  8]] 

This id 2D Array:
[[1 5 9 5]
 [2 9 7 1]] 

This id 3D Array:
[[[1.1 5.7 7.  9. ]
  [2.  7.1 8.  9. ]
  [3.  4.  9.  8. ]]]


In [32]:
# size function
print("No. of elements in the array x,y,z respectively:")
print(x.size)
print(y.size)
print(z.size)

No. of elements in the array x,y,z respectively:
4
8
12


In [33]:
# shape function
print("No. of rows,cols in the array x,y,z respectively:")
print(x.shape)
print(y.shape)
print(z.shape)

No. of rows,cols in the array x,y,z respectively:
(1, 4)
(2, 4)
(1, 3, 4)


In [34]:
# dtype function
print("Type of data present in the array:")
print(x.dtype)
print(y.dtype)
print(z.dtype)

Type of data present in the array:
int32
int32
float64


In [35]:
# transpose of array
print("Transpose of array z:")
print(z.transpose())

Transpose of array z:
[[[1.1]
  [2. ]
  [3. ]]

 [[5.7]
  [7.1]
  [4. ]]

 [[7. ]
  [8. ]
  [9. ]]

 [[9. ]
  [9. ]
  [8. ]]]


In [36]:
# Concatenate function
a=np.concatenate((x,x),axis=0)
print(a,"\n")
b=np.concatenate((x,x),axis=1)
print(b,"\n")
c=np.concatenate((x,x),axis=None)
print(c)

[[ 2  5 10  8]
 [ 2  5 10  8]] 

[[ 2  5 10  8  2  5 10  8]] 

[ 2  5 10  8  2  5 10  8]


In [42]:
# MaskedArray
x1=np.ma.arange(1,5)
print(x1)
x1[1]=np.ma.masked  
print(x1)

[1 2 3 4]
[1 -- 3 4]


In [50]:
# append array
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(11,20).reshape(3,3)
a3=np.append(a1,a2,axis=0)
print(a3,"\n")
a4=np.append(a1,a2,axis=1)
print(a4,"\n")
a5=np.append(a1,a2,axis=None)
print(a5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]] 

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]] 

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
